package General;

public enum Properties {
	TYPE, NUM_NETWORKS, TIMING, ACTIVATION, COMPETING, SPECIATION_THRESHHOLD, ADJUST, RANDOM, DISABLE, NEW_GENE, EXISTING_LAYER, ALLOWED_ERROR, LEARNING_RATE, MOMENTUM
}
